### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Ejstn** [ikem-cz/zscanner-android#1]
This application is said to be used by doctors at IKEM yet there is not a single unit test to be found and the code looks like there are no standards at all on some places, what a shame. But good thing you have your cybersecurity covered

**Comment by jxsv** [comment]
I have created a separate issue for unit tests and renamed this one so we have some actionable items (https://github.com/ikem-cz/zscanner-android/issues/2)
Regarding code style, would you please pinpoint some specific places which lack code style so we can fix it?

**Comment by Ejstn** [comment]
Fair enough

- some fields have "m" in front of them but not all of them, ie: **CreateMessagePatientFragment.kt**

- there is abit of code commented out in **JobsOverviewActivity.kt** and **AutoCompleteDropDown.kt**

- !! operator could be avoided in my opinion

- when observing livedata from fragment, you should pass `viewLifecycleOwner `as `LifecycleOwner`, I recall there is some bug when passed `this`. Explained [here](https://medium.com/@BladeCoder/architecture-components-pitfalls-part-1-9300dd969808)

`        mViewModel.storedSendJobs.observe(**viewLifecycleOwner**, Observer<List<SendJob>> { t ->
            if (t != null) {
                Log.d(TAG, "Observed ${t.size} jobs.")
            }
            if (t != null) {
                jobsAdapter.updateSendJobInfos(t)
            }
        })`

- there should be no czech comments in **Patient.kt**

- **EmptyViewRecyclerView.kt** seems to be silly, I think the way it should be is viewModel should tell view whether to show empty or "normal" layout

- there are unused methods in **Utils.kt**

- there are inconsitent new lines/formatting ie: **fragment_login.xml**, **fragment_message_pages.xml**, **fragment_message_patient.xml**
